name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim
    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URI: postgresql://postgres:pgs3cr3t@postgres:5432/testdb
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel


  
      - name: Debug DATABASE_URI
        run: echo $DATABASE_URI

      - name: Verify SQLAlchemy PostgreSQL dialect
        run: |
          python -c "
          from sqlalchemy.dialects import registry;
          print(registry.load('postgresql'))
          "
